### ISSUE TITLE
Cannot be launched when not connected to the internet

### ISSUE THREAD

**Issue by probonopd** [doomlerd/PreMiD-Linux#1]
Cannot be launched when not connected to the internet:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/0cd4cf40b6d9b2022b055fe51f9cf32986f827dd/database/PreMiD/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1904

**Comment by doomlerd** [comment]
Never mind, I'll see if I can fix the issue later.

**Comment by doomlerd** [comment]
Fixed in v2.1.3.
