### ISSUE TITLE
Adding a inverted color icon.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [doomlerd/PreMiD-Linux#13]
**Is your feature request related to a problem? Please describe.**
The PreMid application, has only a white icon, making it fade easily in the notification tray for those having a clear bright dock.
![image](https://user-images.githubusercontent.com/13170204/76140601-82722d80-605c-11ea-8b31-eb895aef43e8.png)
![image](https://framapic.org/lKYjiWI8UZZ9/yEtg0AfLpd1y.gif)
*Demonstrated on the ZorinOS GNOME dock.*
**Describe the solution you'd like**
Have either an option, to switch to a colored icon, which should help to contrast more on the notification tray.
![image](https://framapic.org/O6PgJCrRsV7O/8OTyPaW7nb17.gif)
*Demonstrated with the [ckb-next application](https://github.com/ckb-next/ckb-next)*
Or better, having a bright and dark icon switch in the settings.
![image](https://framapic.org/jilIj8C9br43/R2QvRvU5ZxCO.gif)
*Demonstrated with the [Habits](https://github.com/atareao/habits) application.*

**Comment by doomlerd** [comment]
This is more likely an issue with upstream, but I'll see if I can do anything about it.

**Comment by doomlerd** [comment]
Hello @PoorPocketsMcNewHold sorry but can you please repost your issue in https://github.com/PreMiD/Linux ? The repository has been moved.
